function SelectImgs()
close all;
global SE paths;
paths = cell(1,6);
SE.window = figure('units', 'pixels',...
                'position', [300 150 1000 600],...
                'menubar', 'figure',...
                'name', 'Magic Cube',...
                'numbertitle', 'off',...
                'resize', 'on');
% 选择第1张图片
SE.selectFileButton(1) = uicontrol('parent',SE.window,...
                                 'style','pushbutton',...
                                 'string','选择图片1',...
                                 'position',[100,500,200,30],...
                                 'visible','on',...
                                 'callback',{@SelectImage, 1});
                             
SE.showFilePathText(1) = uicontrol('parent',SE.window,...
                                 'style','edit',...
                                 'string','.\testpic\1.bmp',...
                                 'position',[100,470,300,30]);
% 选择第2张图片                     
SE.selectFileButton(2) = uicontrol('parent',SE.window,...
                                 'style','pushbutton',...
                                 'string','选择图片2',...
                                 'position',[100,420,200,30],...
                                 'visible','on',...
                                 'callback',{@SelectImage, 2});
                             
SE.showFilePathText(2) = uicontrol('parent',SE.window,...
                                 'style','edit',...
                                 'string','.\testpic\2.bmp',...
                                 'position',[100,390,300,30]);
% 选择第3张图片
SE.selectFileButton(3) = uicontrol('parent',SE.window,...
                                 'style','pushbutton',...
                                 'string','选择图片3',...
                                 'position',[100,340,200,30],...
                                 'visible','on',...
                                 'callback',{@SelectImage, 3});
                             
SE.showFilePathText(3) = uicontrol('parent',SE.window,...
                                 'style','edit',...
                                 'string','.\testpic\3.bmp',...
                                 'position',[100,310,300,30]);
% 选择第4张图片           
SE.selectFileButton(4) = uicontrol('parent',SE.window,...
                                 'style','pushbutton',...
                                 'string','选择图片4',...
                                 'position',[100,260,200,30],...
                                 'visible','on',...
                                 'callback',{@SelectImage, 4});
                             
SE.showFilePathText(4) = uicontrol('parent',SE.window,...
                                 'style','edit',...
                                 'string','.\testpic\4.bmp',...
                                 'position',[100,230,300,30]);
% 选择第5张图片         
SE.selectFileButton(5) = uicontrol('parent',SE.window,...
                                 'style','pushbutton',...
                                 'string','选择图片5',...
                                 'position',[100,180,200,30],...
                                 'visible','on',...
                                 'callback',{@SelectImage, 5});
                             
SE.showFilePathText(5) = uicontrol('parent',SE.window,...
                                 'style','edit',...
                                 'string','.\testpic\5.bmp',...
                                 'position',[100,150,300,30]);
                             
% 选择第6张图片         
SE.selectFileButton(6) = uicontrol('parent',SE.window,...
                                 'style','pushbutton',...
                                 'string','选择图片6',...
                                 'position',[100,100,200,30],...
                                 'visible','on',...
                                 'callback',{@SelectImage, 6});
                             
SE.showFilePathText(6) = uicontrol('parent',SE.window,...
                                 'style','edit',...
                                 'string','.\testpic\6.bmp',...
                                 'position',[100,70,300,30]);
            
SE.confirm = uicontrol('parent',SE.window,...
                             'style','pushbutton',...
                             'string','确认',...
                             'position',[500,325,100,50],...
                             'visible','on',...
                             'callback',@Confirm);
                 
end

function Confirm(~,~)
    global SE paths R RGB;
    for i = 1:6
        paths{1,i} = get(SE.showFilePathText(i),'string');
        disp(paths{1,i});
    end
    disp('图片路径选择完毕');
    pic_cell = cell(1,6);
    for i = 1:6
        fprintf("\n识别第%d张图片\n",i);
        pic_cell{1,i} = get_magic_face(imread(paths{1,i}));
        imshow(pic_cell{1,i});
    end
    [R,RGB] = color_detection(pic_cell, 3);
    
    ReviseColor();
end

function SelectImage(~,~,id)
    global SE;
    [filename,pathname] = uigetfile({'*.bmp';'*.png';'*.bmp'}, '请选择图片文件');
    path = strcat(pathname,filename);
    if strlength(path) > 0
        set(SE.showFilePathText(id),'string',path);
    end
end